name:                xanthous
version:             0.1.0.0
github:              "glittershark/xanthous"
license:             GPL-3
author:              "Griffin Smith"
maintainer:          "root@gws.fyi"
copyright:           "2019 Griffin Smith"

extra-source-files:
- README.org

synopsis:            A WIP TUI RPG
category:            Game

description:         Please see the README on GitHub at <https://github.com/glittershark/xanthous>

dependencies:
- base

- aeson
- QuickCheck
- quickcheck-text
- quickcheck-instances
- brick
- checkers
- classy-prelude
- constraints
- containers
- data-default
- deepseq
- file-embed
- filepath
- generic-arbitrary
- generic-monoid
- groups
- lens
- megaparsec
- MonadRandom
- mtl
- random
- raw-strings-qq
- reflection
- stache
- tomland
- vty
- yaml

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- NoImplicitPrelude
- NoStarIsType
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -Wall

library:
  source-dirs: src

executable:
  source-dirs: src
  main: Main.hs
  dependencies:
  - xanthous
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xanthous
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - lens-properties
