[Creature]
name = "gormlak"
description = "A gormlak"
long_description = """
A chittering imp-like creature with bright yellow horns. It adores shiny objects
and gathers in swarms.
"""
char = { char = "g", color = "red" }
max_hitpoints = 5
speed = 120
friendly = false
