version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  build:
    executor: rust/default
    steps:
      - checkout
      - rust/update_toolchain
      - rust/build
  test:
    executor: rust/default
    steps:
      - checkout
      - rust/update_toolchain
      - rust/test
  format:
    executor: rust/default
    steps:
      - checkout
      - rust/update_toolchain
      - rust/format
  lint:
    executor: rust/default
    steps:
      - checkout
      - rust/update_toolchain
      - rust/clippy
workflows:
  default:
    jobs:
      - lint
      - format
      - build
      - test:
          requires:
            - build
