[global]
welcome = "Welcome to Xanthous! It's dangerous out there, why not stay inside?"

[combat]
attack = "You attack the {{creature.name}}."
killed = [
    "You've killed the {{creature.name}}.",
    "The {{creature.name}} dies.",
    "The {{creature.name}} kicks it.",
    "The {{creature.name}} beefs it."
    ]
