[global]
welcome = "Welcome to Xanthous, {{character.name}}! It's dangerous out there, why not stay inside?"
describe_entities = "You see here {{descriptions}}"
describe_no_entities = "You see nothing here."
pick_up = "You pick up the {{item.name}}."

[combat]
attack = "You attack the {{creature.name}}."
attack.menu = "Which creature would you like to attack?"
killed = [
    "You've killed the {{creature.name}}.",
    "The {{creature.name}} dies.",
    "The {{creature.name}} kicks it.",
    "The {{creature.name}} beefs it."
    ]

[character]
name_prompt = [
    "Hey there friend. What's your name?",
    "Hey there friend. What should we call you?",
    "Howdy. What's your name?",
    "Name please!",
    "What's your name?",
    "Hey, what's your name?",
]

[defaults.item]
eat = "You eat the {{item.name}}. {{action.result}}"
